---
kind: pipeline
type: docker
name: build

trigger:
  event:
  - tag

steps:

- name: Validate composer syntax
  image: webdevops/php-nginx:7.3
  commands:
    - cd docker
    - composer --no-interaction validate

- name: Validate shell scripts syntax
  image: koalaman/shellcheck-alpine
  environment:
    SHELLCHECK_OPTS: "-e SC2154"
  commands:
    - find -type f -iname '*.sh' -exec shellcheck {} +

- name: Build LEDStrain docker image and push to registry
  image: plugins/docker
  settings:
    use_cache: true
    repo:
      from_secret: DOCKER_REGISTRY_REPO
    username:
      from_secret: DOCKER_REGISTRY_USERNAME
    password:
      from_secret: DOCKER_REGISTRY_PASSWORD
    registry:
      from_secret: DOCKER_REGISTRY_URL
    tags:
      - latest
      - ${DRONE_TAG}
    dockerfile: docker/Dockerfile
    context: docker/

---
kind: pipeline
type: docker
name: deployment

trigger:
  event:
  - promote
  target:
  - production

steps:

- name: Deploy to staging
  image: plugins/ansible:3
  settings:
    playbook: ansible/site.yml
    galaxy: ansible/requirements.yml
    inventory: ansible/inventory
    vault_password:
      from_secret: ANSIBLE_VAULT_PASSWORD
    private_key:
      from_secret: STAGING_SERVER_SSH_PRIVATE
    tags:
      - staging
    extra_vars: version=${DRONE_TAG}
---
kind: signature
hmac: 0a5d29c95a2ae00fdc7c90d23b3c1b4fe82c9ea4a79543baff6b282eb55bebda

...
