---
kind: pipeline
type: docker
name: build

trigger:
  event:
  - tag

steps:

- name: Validate composer syntax
  image: webdevops/php-nginx:7.3
  commands:
    - cd docker
    - composer --no-interaction validate

- name: Validate shell scripts syntax
  image: koalaman/shellcheck-alpine
  environment:
    SHELLCHECK_OPTS: "-e SC2154"
  commands:
    - find -type f -iname '*.sh' -exec shellcheck {} +

- name: Build LEDStrain docker image and push to registry
  image: plugins/docker
  settings:
    use_cache: true
    repo:
      from_secret: DOCKER_REGISTRY_REPO
    username:
      from_secret: DOCKER_REGISTRY_USERNAME
    password:
      from_secret: DOCKER_REGISTRY_PASSWORD
    registry:
      from_secret: DOCKER_REGISTRY_URL
    build_args_from_env:
      - EXTIVERSE_TOKEN
    tags:
      - latest
      - ${DRONE_TAG}
    dockerfile: docker/Dockerfile
    context: docker/
  environment:
    EXTIVERSE_TOKEN:
      from_secret: EXTIVERSE_TOKEN

---
kind: pipeline
type: docker
name: deployment

trigger:
  event:
  - promote
  target:
  - production

steps:

- name: Deploy to production
  image: plugins/ansible:3
  settings:
    playbook: ansible/site.yml
    galaxy: ansible/requirements.yml
    inventory: ansible/inventory
    vault_password:
      from_secret: ANSIBLE_VAULT_PASSWORD
    private_key:
      from_secret: DRONE_SSH_PRIVATE
    extra_vars: version=${DRONE_TAG}
---
kind: signature
hmac: 2f67c1f7a93529aeb72cac0b944a3d237420d97f4a3f9f4823ded284420c9d40

...
