version: '3.3'

services:
  forum:
    build:
      context: ./docker
      target: dev
      args:
        - EXTIVERSE_TOKEN=${EXTIVERSE_TOKEN}
    labels:
      caddy: "${HOSTNAME}"
      caddy.reverse_proxy: "{{ upstreams 80 }}"
      caddy.reverse_proxy.health_uri: '/api/posts/1'
      caddy.reverse_proxy.lb_try_duration: '60s'
      caddy.reverse_proxy.lb_try_interval: '5s'
      caddy.header: /assets
      caddy.header.+Cache-Control_0: "public, must-revalidate, proxy-revalidate"
      caddy.header.+Cache-Control_1: "max-age=25000"
      caddy.header.Pragma: "public"
    volumes:
      - "./data/forum/conf:/conf"
      - "./data/forum/data/storage/sessions:/app/storage/sessions"
      - "./data/forum/data/composer_cache:/root/.composer/cache"
#     - "./data/forum/data/public/assets:/app/public/assets"
      - "./data/forum/data/public/assets/avatars:/app/public/assets/avatars"
      - "./data/forum/data/public/assets/files:/app/public/assets/files"
      - "./data/forum/data/public/assets/images:/app/public/assets/images"
    environment:
      INSTALL:         "${INSTALL}"
      hc_schedule:     ${hc_schedule}
      PUID_ID:         ${PUID_ID}
      HOSTNAME:        ${HOSTNAME}
      MASTER_TOKEN:    ${MASTER_TOKEN}
      DB_HOST:         ${DB_HOST}
      DB_NAME:         ${MYSQL_DATABASE}
      DB_USER:         ${MYSQL_USER}
      DB_PASS:         ${MYSQL_PASSWORD}
    logging:
      driver: "json-file"
    ports:
      - 6001:6001
    depends_on:
      db:
        condition: "service_healthy"
      redis:
        condition: "service_started"
    networks:
      - internal
      - public
  redis:
    image: redis:6
    restart: unless-stopped
    volumes:
#   - './data/redis/conf:/usr/local/etc/redis:ro'
    - './data/redis/data:/data:rw'
    entrypoint: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    logging:
      driver: "json-file"
    networks:
    - internal
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:      ${MYSQL_DATABASE}
      MYSQL_USER:          ${MYSQL_USER}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}
    volumes:
      - "./data/db/data:/var/lib/mysql"
    logging:
      driver: "json-file"
    healthcheck:
      test: "/usr/bin/mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --execute \"SELECT 1;\""
      timeout: 2s
      interval: 10s
      retries: 5
      start_period: 4s
    networks:
      - internal
  phpmyadmin:
    image: phpmyadmin
    labels:
      caddy: ${PHPMYADMIN_HOSTNAME}
      caddy.reverse_proxy: "{{ upstreams 80 }}"
    logging:
      driver: "json-file"
    environment:
      PMA_HOST: db
      PMA_ABSOLUTE_URI: ${PHPMYADMIN_HOSTNAME}
      PMA_USER:         root
      PMA_PASSWORD:     ${MYSQL_ROOT_PASSWORD}
    networks:
      - internal
      - public

  ledstrain_directus:
    image: docker.xyzz.work/server/directus:10
    labels:
      caddy: '${PUBLIC_URL}'
      caddy.reverse_proxy: '{{ upstreams 8055 }}'
    environment:
      PUBLIC_URL: 'https://${PUBLIC_URL}/'
      KEY: '${KEY}'
      SECRET: '${SECRET}'
      ADMIN_EMAIL: '${ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${ADMIN_PASSWORD}'
      WEBSOCKETS_ENABLED: '${WEBSOCKETS_ENABLED}'
      CACHE_ENABLED: '${CACHED_ENABLED}'
      CACHE_TTL: '${CACHE_TTL}'
      CACHE_AUTO_PURGE: '${CACHE_AUTO_PURGE}'

      DB_CLIENT: '${DB_CLIENT}'
      DB_HOST: '${DB_HOST}'
      DB_PORT: '${DB_PORT}'
      DB_DATABASE: '${MYSQL_DATABASE}'
      DB_USER: '${MYSQL_USER}'
      DB_PASSWORD: '${MYSQL_PASSWORD}'

      FLOWS_EXEC_ALLOWED_MODULES: 'array:${FLOWS_EXEC_ALLOWED_MODULES}'
    networks:
      - public
      - internal

networks:
  internal:
  public:
    external: true
