version: '3.3'

services:
  forum:
    build:
      context: ./docker
      target: dev
      args:
        - EXTIVERSE_TOKEN=${EXTIVERSE_TOKEN}
    labels:
      caddy: "${HOSTNAME}"
      caddy.reverse_proxy: "{{ upstreams 80 }}"
    volumes:
      - "./data/forum/conf:/conf"
      - "./data/forum/data/storage/sessions:/app/storage/sessions"
      - "./data/forum/data/composer_cache:/root/.composer"
#     - "./data/forum/data/public/assets:/app/public/assets"
      - "./data/forum/data/public/assets/avatars:/app/public/assets/avatars"
      - "./data/forum/data/public/assets/files:/app/public/assets/files"
      - "./data/forum/data/public/assets/images:/app/public/assets/images"
    environment:
      INSTALL:         "${INSTALL}"
      hc_schedule:     ${hc_schedule}
      PUID_ID:         ${PUID_ID}
      HOSTNAME:        https://${HOSTNAME}
      MYSQL_DATABASE:  ${MYSQL_DATABASE}
      MYSQL_USER:      ${MYSQL_USER}
      MYSQL_PASSWORD:  ${MYSQL_PASSWORD}
    depends_on:
      db:
        condition: "service_healthy"
    networks:
      - internal
      - caddy
  db:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:      ${MYSQL_DATABASE}
      MYSQL_USER:          ${MYSQL_USER}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}
    volumes:
      - "./data/db/data:/var/lib/mysql"
    healthcheck:
      test: "/usr/bin/mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --execute \"SELECT 1;\""
      timeout: 2s
      interval: 10s
      retries: 5
      start_period: 4s
    networks:
      - internal

networks:
  internal:
  caddy:
    external: true
