version: '3.3'

services:
  forum:
    build:
      context: ./docker
      target: dev
      args:
        - EXTIVERSE_TOKEN=${EXTIVERSE_TOKEN}
    labels:
      caddy: "${HOSTNAME}"
      caddy.reverse_proxy: "{{ upstreams 80 }}"
      caddy.header: /assets
      caddy.header.+Cache-Control_0: "public, must-revalidate, proxy-revalidate"
      caddy.header.+Cache-Control_1: "max-age=25000"
      caddy.header.Pragma: "public"
    volumes:
      - "./data/forum/conf:/conf"
      - "./data/forum/data/storage/sessions:/app/storage/sessions"
      - "./data/forum/data/composer_cache:/root/.composer/cache"
#     - "./data/forum/data/public/assets:/app/public/assets"
      - "./data/forum/data/public/assets/avatars:/app/public/assets/avatars"
      - "./data/forum/data/public/assets/files:/app/public/assets/files"
      - "./data/forum/data/public/assets/images:/app/public/assets/images"
    environment:
      INSTALL:         "${INSTALL}"
      hc_schedule:     ${hc_schedule}
      PUID_ID:         ${PUID_ID}
      HOSTNAME:        ${HOSTNAME}
      IMAGE_VERSION:   ${IMAGE_VERSION}
      MASTER_TOKEN:    ${MASTER_TOKEN}
      MYSQL_DATABASE:  ${MYSQL_DATABASE}
      MYSQL_USER:      ${MYSQL_USER}
      MYSQL_PASSWORD:  ${MYSQL_PASSWORD}
    depends_on:
      db:
        condition: "service_healthy"
      redis:
        condition: "service_started"
    networks:
      - internal
      - caddy
  redis:
    image: redis
    restart: unless-stopped
    volumes:
    - './data/redis/conf:/usr/local/etc/redis:ro'
    entrypoint: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
    - internal
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:      ${MYSQL_DATABASE}
      MYSQL_USER:          ${MYSQL_USER}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}
    volumes:
      - "./data/db/data:/var/lib/mysql"
    healthcheck:
      test: "/usr/bin/mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --execute \"SELECT 1;\""
      timeout: 2s
      interval: 10s
      retries: 5
      start_period: 4s
    networks:
      - internal
  phpmyadmin:
    image: phpmyadmin
    labels:
      caddy: ${PHPMYADMIN_HOSTNAME}
      caddy.reverse_proxy: "{{ upstreams 80 }}"
    environment:
      PMA_HOST: db
      PMA_ABSOLUTE_URI: ${PHPMYADMIN_HOSTNAME}
      PMA_USER:         root
      PMA_PASSWORD:     ${MYSQL_ROOT_PASSWORD}
    networks:
      - internal
      - caddy

networks:
  internal:
  caddy:
    external: true
