services:
  forum:
    image: "${IMAGE}"
    volumes:
      - ledstrain-assets:/app/public/assets
    environment:
      INSTALL:         ${INSTALL:-false}
      hc_schedule:     ${hc_schedule}
      PUID_ID:         ${PUID_ID}
      HOSTNAME:        ${HOSTNAME}
      MASTER_TOKEN:    ${MASTER_TOKEN}
      DB_HOST:         ${DB_HOST}
      DB_NAME:         ${DB_NAME}
      DB_USER:         ${DB_USER}
      DB_PASS:         ${DB_PASS}
    ports:
      - 6001:6001
    networks:
      - internal
      - database
      - public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        caddy: "${HOSTNAME}"
        caddy.reverse_proxy: "{{ upstreams 80 }}"
        caddy.tls.dns: "cloudflare {env.CLOUDFLARE_API}"
      caddy.reverse_proxy.health_uri: '/api/posts/1'
        caddy.reverse_proxy.lb_try_duration: '60s'
        caddy.reverse_proxy.lb_try_interval: '5s'
        caddy.header_0: /assets
        caddy.header_0.+Cache-Control_0: "public, must-revalidate, proxy-revalidate"
        caddy.header_0.+Cache-Control_1: "max-age=25000"
        caddy.header_0.Pragma: "public"
        caddy.header_1: "Strict-Transport-Security max-age=31536000;"
        caddy.route_0: /login
        caddy.route_0.rate_limit: '{cookie.flarum_session} 1r/s'
        caddy.route_1: /api
        caddy.route_1.rate_limit: '{cookie.flarum_session} 60r/m'
        caddy.route_2: /api/forgot
        caddy.route_2.rate_limit: '{cookie.flarum_session} 5r/m'
        caddy.redir: '/donate https://link.sandcatdev.com/ledstrain-donation'
      placement:
        constraints:
          - node.platform.os == linux
          - node.labels.app == ledstrain

networks:
  internal:
  public:
    external: true
  database:
    external: true

volumes:
  ledstrain-assets:
