---

- name: Deploy forum version
  hosts: ledstrain
  tags:
    - staging
    - production
  vars_files:
    - vault.yml
  vars:
    version: "{{ version }}"
    stage:   "{{ stage }}"

  tasks:
    - name: Change version in docker-compose
      lineinfile:
        path: '{{ dockerpath }}/{{ vars[stage]["hostname"] }}/{{ vars[stage]["app"] }}/.env'
        regexp: '^IMAGE_VERSION=".*"'
        line:   'IMAGE_VERSION="{{ version }}"'

    - name: Pull new image
      community.docker.docker_compose:
        project_src: '{{ dockerpath }}/{{ vars[stage]["hostname"]}}/{{ vars[stage]["app"] }}'
        pull: yes
        state: present
      notify:
        - restart_reverse_proxy

    - name: Report site and version
      debug:
        msg: '{{ vars[stage]["hostname"] }} set to {{ version }}'
  handlers:
    - name: restart_reverse_proxy
      community.general.docker_compose:
        project_src: "{{ dockerpath }}/{{ ansible_facts.nodename }}/caddy"
        state: present
        recreate: always
